# -*- coding: utf-8 -*-
"""
Words for the hangman game

Consist of dictionary where a word is key and similar word as value

words taken from https://www.englishlearnsite.com/vocabulary/common-synonym-vocabulary-word-list/

"""
words_list = [['abandon', 'desert'],
              ['abbreviate', 'shorten'],
              ['ability', 'skill'],
              ['able', 'capable'],
              ['above', 'overhead'],
              ['abundant', 'sufficient'],
              ['accurate', 'correct'],
              ['achieve', 'accomplish'],
              ['active', 'energetic'],
              ['adamant', 'firm'],
              ['add', 'increase'],
              ['adequate', 'ample'],
              ['adjourn', 'postpone'],
              ['adult', 'grownup'],
              ['advocate', 'support'],
              ['after', 'following'],
              ['afraid', 'frightened'],
              ['aggressive', 'assertive'],
              ['amateur', 'beginner'],
              ['ambitious', 'aspiring'],
              ['antagonize', 'provoke'],
              ['approve	', 'ratify'],
              ['artificial', 'synthetic'],

              ['ban', 'prohibit'],
              ['barren', 'unproductive'],
              ['bashful', 'timid'],
              ['beautiful', 'pretty'],
              ['before', 'prior'],
              ['beginning', 'initiate'],
              ['believe	', 'trust'],
              [' below', 'under'],
              ['beneficial', 'helpful'],
              ['blend', 'combine'],
              ['broad', 'wide'],

              ['calm', 'tranquil'],
              ['capture', 'apprehend'],
              ['careful	', 'cautious'],
              ['cease', 'stop'],
              ['certain	', 'positive'],
              ['chilly', 'cool'],
              ['coarse', 'bumpy'],
              ['colossal', 'enormous'],
              ['combine', 'blend'],
              ['comical	', 'amusing'],
              ['competent', 'capable'],
              ['comprehend', 'understand'],
              ['concrete', 'real'],
              ['condemn', 'censure'],
              ['confine', 'contain'],
              ['conform', 'comply'],
              ['confuse	', 'complicate'],
              ['convenient', 'handy'],

              ['damage', 'hurt'],
              ['dangerous', 'unsafe'],
              ['daring', 'bold'],
              ['decay', 'spoil'],
              ['deduct', 'subtract'],
              ['defend', 'protect'],
              ['deposit', 'store'],
              ['determined', 'sure'],
              ['die', 'expire'],
              ['different', 'distinct'],
              ['difficult', 'hard'],
              ['dilute', 'weaken'],
              ['dispute', 'debate'],
              ['diverse', 'different'],
              ['divide', 'separate'],
              ['docile', 'tame'],
              ['dormant', 'inactive'],
              ['doubt', 'mistrust'],
              ['dumb', 'stupid'],

              ['early', 'premature'],
              ['easy', 'simple'],
              ['eccentric', 'peculiar'],
              ['ecstasy', 'elation'],
              ['encourage', 'promote'],
              ['enlarge', 'expand'],
              ['enormous', 'immense'],
              ['enough', 'sufficient'],
              ['entirely', 'wholly'],
              ['eternal', 'everlasting'],
              ['evident', 'apparent'],
              ['evil', 'bad'],
              ['exceptional', 'remarkable'],
              ['excite', 'arouse'],
              ['exquisite', 'delightful'],
              ['extravagant', 'extreme'],

              ['fabulous', 'marvelous'],
              ['face', 'confront'],
              ['fair', 'honest'],
              ['fake', 'imitation'],
              ['fantastic', 'incredible'],
              ['fatigue', 'exhaust'],
              ['feasible', '	possible'],
              ['feeble', 'frail'],
              ['ferocious', 'fierce'],
              ['fiction', 'fantasy'],
              ['forbid', 'prohibit'],
              ['forgive', 'pardon'],
              ['former', 'previous'],
              ['fraction', 'portion'],
              ['frank', 'candid'],
              ['fresh', 'unused'],
              ['friend', 'comrade'],
              ['frigid', 'freezing'],
              ['frivolous', 'trivial'],
              ['furious	', 'infuriated'],

              ['gain', 'receive'],
              ['gallant', 'stately'],
              ['gather', 'collect'],
              ['gaudy', 'vulgar'],
              ['gaunt', 'skinny'],
              ['generous', 'giving'],
              ['gentle	', 'mild'],
              ['genuine', 'authentic'],
              ['gigantic', 'colossal'],
              ['give', 'donate'],
              ['glad', 'pleased'],
              ['gloomy	', 'dismal'],
              ['glorious', 'splendid'],
              ['good', 'nice'],
              ['gorgeous', 'ravishing'],
              ['gratitude', 'thankfulness'],
              ['great', 'outstanding'],

              ['handy', 'skillful'],
              ['hard', 'firm'],
              ['hate', 'detest'],
              ['honest', 'truthful'],

              ['immaculate', 'spotless'],
              ['immature', 'childish'],
              ['immune', 'resistant'],
              ['irritate', 'annoy'],

              ['join', 'connect'],
              ['jolly', 'joyful'],
              ['kind', 'considerate'],

              ['lament	', 'grieve'],
              ['large', 'massive'],
              ['last', 'final'],
              ['luxurious', 'extravagant'],

              ['magnify', 'expand'],
              ['mandatory', 'required'],
              ['maneuver', 'manipulate'],
              ['mysterious', 'elusive'],

              ['naughty', 'wrong'],
              ['neat', 'clean'],
              ['normal', 'ordinary'],
              ['numerous', 'several'],

              ['obey', 'mind'],
              ['oblivious', 'unconscious'],
              ['outstanding', 'extraordinary'],

              ['passive', 'compliant'],
              ['patience', 'tolerance'],
              ['peculiar', 'weird'],
              ['perfect', 'flawless'],
              ['proud', 'arrogant'],

              ['qualified', 'competent'],
              ['question', 'interrogate'],
              ['quiet', 'silent'],

              ['racket', 'commotion'],
              ['radiant', 'luminous'],
              ['risky', 'hazardous'],
              ['rowdy', 'boisterous'],
              ['rude', 'impolite'],

              ['spontaneous', 'instinctive'],
              ['stable', 'settled'],
              ['stationary', 'firm'],
              ['successful', 'triumphant'],

              ['tall', 'high'],
              ['taut', 'tense'],
              ['turmoil', 'commotion'],

              ['unbiased', 'impartial'],
              ['upset', 'perturb'],
              ['urgent', 'crucial'],

              ['vacant	', 'unoccupied'],
              ['victory', 'triumph'],
              ['virtuous', 'moral'],
              ['vulgar', 'offensive'],

              ['wealth	', 'prosperity'],
              ['weary', 'lethargic'],
              ['wholehearted', 'earnest'],
              ['wild', 'uncivilized'],
              ['win', 'triumph'],
              ['wise', 'knowing'],
              ['wonderful', 'marvelous'],
              ['worn', 'used'],
              ['wrong', 'incorrect']]

# print(words_list)